/*
=================================================================
DDL Script: Create Gold Views
=================================================================
Script purpose:
    This sript create views for 'Gold' layer in the data warehouse.
    The 'Gold' layer represents the final dimention and fact tables (Star Schema)

    Each view perfoms transformations and combine data from the 'Silver' layer
    to produce clean, enriched, and business ready datasets.

Usage:
    -These views can be queried directly for analytics and reporting.
=======================================================================
/*

--- ===================================================================
--- Create Dimension: gold.dim_customers
--- ===================================================================

--- ===================================================================
--- Create Dimension: gold.dim_customers
--- ===================================================================

--- ===================================================================
--- Create Dimension: gold.dim_customers
--- ===================================================================
